apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apache-data
  namespace: ludo-forma
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 150Mi
