apiVersion: v1
kind: Service
metadata:
  name: web
  #namespace: default
  labels:
    app: web
  annotations:
    # set to true if you want our custom prometheus scraper job to gather custom metrics
    prometheus.io/path: /metrics
    prometheus.io/scrape: "false"
spec:
  ports:

  - port: 8080 # available at this service
    name: http
    targetPort: 8080 # exposed from inside container
    protocol: TCP

  - port: 9117 # available at this service
    name: metrics # ends with 'metrics' in case we want custom scraper to recognize
    targetPort: 9117 # exposed from inside container
    protocol: TCP

  selector:
    app: web
