apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data
  labels:
    app: db
  namespace: forma-ludo
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
