apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code
  namespace: forma-ludo
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
  storageClassName: nfs-storage
