kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: x-nfs
  namespace: web
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
